### ISSUE TITLE
Nonexistant Chapter 15 in "Mastering Ethereum"

### ISSUE THREAD

**Issue by Am0rfu5** [slowmist/SlowMist-Learning-Roadmap-for-Becoming-a-Smart-Contract-Auditor#2]
Under the "Basics of Blockchain" of the README.md there is a reference to chapter 15 but the final chapter in the book is chapter 13.

- Reading "[Mastering Ethereum](https://github.com/ethereumbook/ethereumbook)"
    - Emphasis should be on Chapters 1, 4, 5, 6, 7, 13, and **15**

**Comment by Kong-F** [comment]
Ohh.. Yes, you are right, Chapter 15 does not exist. I corrected this, thank you!
